### PR TITLE
Name and links edit component

### PR DESCRIPTION
**Pull request by ayaali333**
Name And Links Component 
this PRs #46

### CODE REVIEW

**Review by AllanSaleh — CHANGES_REQUESTED** [review]
Good work, @ayaali333 !

There are some changes I will need you to make:
- Add some space between the two components.
image
- Add the Resume title for the second component just like the image in the issue:
197367743-ce0aca61-223d-4b8b-b680-26354be0f074
- Please make the component responsive.
image

**Review by AllanSaleh — CHANGES_REQUESTED** [review]
Great work on making a lot of progress!!👏

It is still not fully responsive on mobile phones. This is the only thing left then I will be able to merge it!

Keep up the great work!🙌

**Comment by ayaali333** [comment]
Edit Input  #RPs 46

**Review by AllanSaleh — APPROVED** [review]
Great work on making it responsive!!🙌
LGTM!!

**Pull request merged**
